---
title       : Housing Finance Application Prototype
subtitle    : Building a Competitive Edge
author      : Anonymous
job         : Coursera Data Science Specialization
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## State of the Low Income Housing Market

1. A well supported housing finance landscape and presence of companies specialized to meet the lower end of the market has helped make Housing supply accessible to low-income customers

2. These specialized housing finance companies have been able to build a quality portfolio

3. There is a tremondous built-up demand at the bottom of the pyramid and this is reflected in the high growth rates of these companies

4. These companies are now spreading to the hinterland as well and meeting in some ways the objective of financial inclusion. 


---

## Key Challenges to sustaining profitable growth

1. Access to debt is a concern with most of these companies having debt/equity ratio of 2:1 or lower

2. There is an additional issue of high cost of debt.

3. Lending rates have therefore been in the range 5-7% which are significantly higher than regular housing loans

3. Lowering the overall cost of operations can play a significant role in addressing this challenge



---

## Cost of Operations

1. Cumulative Costs is at 4.5% ( Refer Black Dotted Line)
2. Average Lending Rate ( including Processing Fee) is at 5.5% ( Refer horizontal Cyan color line)

```{r echo=FALSE,fig.width=8, fig.height=5}
CostHead=c("1.Cost of Funds %","2.Customer Acquisition Cost %","3.Operations Cost %","4.Provision for Bad Debts %")
Percentage=c(3,0.5,0.5,0.5)
a=as.data.frame(cbind(CostHead,Percentage))
a$Percentage=as.numeric(a$Percentage)
plot(Percentage,col=a$CostHead,type="p",lwd=4,main=" Cost Structure",xlab= "Cost",ylab=" Percentage Cost ( Absolute)",ylim=c(0,9))
abline(2.5,0.5,col="black",lwd=2)
abline(5.5,0,col="violet",lwd=2)
legend('topright', CostHead ,col=c('brown', 'red', 'green',' blue'),  text.col=c('brown', 'red', 'green',' blue'), bty='n', cex=0.75)

```


---

## Proposed Solution to Key Challenge

1. Reduce Cost of Operations, Customer Acquisition Cost and Provisions for Bad Debts

2. Build model to ensure loan portfolio is healthy by limiting eligibility and with appropriate pegging of risk - interest rate

3. Build a self service model that initiates origination process on a website, having lesser intermediaries, lower marketing costs and higher reach

4. The prototype built using shiny gives a glimpse of this business model


